# 并非真正的配置文件，需要将这个配置文件放入到nacos中

server:
  port: 5001 # 应用启动端口

spring:
   application:
     name: cloudstudy-auth # 应用名，也是显示在注册中心的名字
# 配置中心
   cloud:
     nacos:
      discovery:
         server-addr: 127.0.0.1:8848

# 数据库配置，暂时使用最简单的配置方式
   datasource:
     url: jdbc:mysql://127.0.0.1:3306/auth?characterEncoding=utf8&connectTimeout=1000&socketTimeout=3000&autoReconnect=true&useSSL=false
     username: root
     password: root
     driver-class-name: com.mysql.jdbc.Driver

citizenstudy:
    jwt:
       sign-key: citizenstudy


info:
  app:
    name: "@project.artifactId@"
    encoding: '@project.build.sourceEncoding@'
    java:
      source: '@java.version@'
      target: '@java.version@'
